-- Run this in Supabase SQL Editor.
create table if not exists public.quizzes (
  id bigint generated by default as identity primary key,
  title text not null,
  time integer not null default 0,
  questions jsonb not null,
  created_at timestamptz not null default now()
);

-- For a simple private/friends-only prototype.
alter table public.quizzes enable row level security;

create policy "public can read quizzes"
on public.quizzes for select
to anon
using (true);

create policy "public can insert quizzes"
on public.quizzes for insert
to anon
with check (true);

create policy "public can delete quizzes"
on public.quizzes for delete
to anon
using (true);
